'use client';
import { useEffect, useState } from 'react';
import { Building2, LayoutDashboard, BriefcaseBusiness, Users, ShieldCheck, PanelLeft, ChevronDown, ChevronRight, Search, Plus, ArrowUpRight, Globe2, FolderKanban } from 'lucide-react';
import { Sidebar, SidebarProvider, SidebarHeader, SidebarContent, SidebarFooter, SidebarGroup, SidebarMenu, SidebarMenuItem, SidebarMenuButton, SidebarInset, useSidebar } from '@/components/ui/sidebar';
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuItem } from '@/components/ui/dropdown-menu';
import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from '@/components/ui/table';
import { TooltipProvider } from '@/components/ui/tooltip';
import { copy, type Language } from './translations';
type Page = 'overview' | 'customers' | 'sales' | 'users' | 'roles' | 'profile';
const customers = [['AC','Atlas Commerce','CUS-001','Retail','Narin S.',3,'active'],['NP','Northstar Property','CUS-002','Property','Pim W.',2,'active'],['HL','Horizon Logistics','CUS-003','Logistics','Narin S.',4,'active'],['ST','Summit Technology','CUS-004','Technology','Krit P.',1,'active'],['GF','Greenfield Foods','CUS-005','Food','Pim W.',2,'archived']] as const;
const nav = [{id:'overview',icon:LayoutDashboard},{id:'customers',icon:Building2},{id:'sales',icon:BriefcaseBusiness},{id:'users',icon:Users},{id:'roles',icon:ShieldCheck}] as const;
function Workspace(){
 const [lang,setLang]=useState<Language>('th'); const [page,setPage]=useState<Page>('customers'); const [query,setQuery]=useState(''); const [notice,setNotice]=useState(false);
 const {toggleSidebar,setOpenMobile,state}=useSidebar(); const t=copy[lang];
 useEffect(()=>{document.documentElement.lang=lang},[lang]);
 function navigate(id:Page){setPage(id);setOpenMobile(false);setNotice(false);requestAnimationFrame(()=>document.getElementById('page-title')?.focus())}
 const rows=customers.filter(r=>r.join(' ').toLowerCase().includes(query.toLowerCase()));
 return <><a className="skip" href="#content">{t.skip}</a><Sidebar collapsible="icon"><SidebarHeader className="brand"><span className="brand-mark"><FolderKanban size={22}/></span><div className="brand-copy"><strong>Project Info</strong><small>WORKSPACE</small></div></SidebarHeader><SidebarContent><SidebarGroup><p className="nav-caption">{t.workspace}</p><SidebarMenu>{nav.map(({id,icon:Icon},i)=><SidebarMenuItem key={id}>{i===3&&<p className="nav-caption admin-caption">{t.administration}</p>}<SidebarMenuButton className="nav-item" tooltip={t[id]} isActive={page===id} aria-current={page===id?'page':undefined} onClick={()=>navigate(id)}><Icon/><span>{t[id]}</span>{id==='customers'&&<span className="nav-count">5</span>}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarGroup></SidebarContent><SidebarFooter><div className="workspace-note"><span className="status-dot"/>{t.demo}</div><button className="collapse-button" onClick={toggleSidebar} aria-label={t.toggle}><PanelLeft size={18}/><span>{state==='expanded'?t.collapse:t.expand}</span></button></SidebarFooter></Sidebar>
 <SidebarInset className="workspace-main"><header className="topbar"><div className="crumb"><button className="icon-button" onClick={toggleSidebar} aria-label={t.toggle}><PanelLeft size={19}/></button><span className="crumb-root">{t.workspace}</span><ChevronRight size={14}/><strong>{t[page]}</strong></div><div className="header-right"><div className="language" aria-label={t.language}><Globe2 size={16}/>{(['th','en'] as const).map(l=><button key={l} aria-pressed={lang===l} onClick={()=>setLang(l)}>{l==='th'?'ไทย':'EN'}</button>)}</div><DropdownMenu><DropdownMenuTrigger className="user-trigger" aria-label={t.userMenu}><span className="avatar">JD</span><span className="user-name">Demo Admin<small>{t.admin}</small></span><ChevronDown size={15}/></DropdownMenuTrigger><DropdownMenuContent align="end" className="min-w-48"><DropdownMenuItem onClick={()=>navigate('profile')}>{t.profile}</DropdownMenuItem><DropdownMenuItem onClick={()=>setNotice(true)}>{t.logout}</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div></header>
 <main id="content" className="content"><div className="eyebrow">{t.section}</div><div className="page-heading"><div><h1 id="page-title" tabIndex={-1}>{t[page]}</h1><p>{t.descriptions[page]}</p></div>{page==='customers'&&<button className="primary-button" onClick={()=>setNotice(true)}><Plus size={18}/>{t.add}</button>}</div>{notice&&<div className="notice" role="status">{t.prototypeNotice}<button onClick={()=>setNotice(false)} aria-label={t.close}>×</button></div>}
 {(page==='customers'||page==='overview')&&<><div className="stats"><div><span>{t.totalCustomers}</span><strong>5 <Building2/></strong><small>{t.demoData}</small></div><div><span>{t.activeCustomers}</span><strong>4 <span className="metric-dot"/></strong><small>{t.ready}</small></div><div><span>{t.openOpportunities}</span><strong>12 <ArrowUpRight/></strong><small>{t.acrossCustomers}</small></div></div><section className="data-panel"><div className="panel-title"><div><h2>{t.customerDirectory}</h2><span className="count-badge">5</span></div><span className="muted">{t.demoData}</span></div><div className="toolbar"><label className="search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={t.search} aria-label={t.search}/></label><span className="muted">{t.allCustomers}</span></div><Table><TableHeader><TableRow>{[t.company,t.industry,t.owner,t.opportunities,t.status].map(label=><TableHead key={label}>{label}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.map((r,i)=><TableRow key={r[2]}><TableCell><div className="company-cell"><span className={`company-avatar color-${i%4}`}>{r[0]}</span><div><strong>{r[1]}</strong><small>{r[2]}</small></div></div></TableCell><TableCell>{t.industries[r[3]]}</TableCell><TableCell><span className="owner-initial">{r[4][0]}</span>{r[4]}</TableCell><TableCell><span className="opportunity-number">{r[5]}</span> {t.items}</TableCell><TableCell><span className={`badge ${r[6]}`}><span/>{t[r[6]]}</span></TableCell></TableRow>)}</TableBody></Table>{rows.length===0&&<div className="empty">{t.noResults}</div>}<footer className="table-footer"><span>{t.showing} {rows.length} / 5</span><span>{t.page} 1 / 1</span></footer></section></>}
 {page==='sales'&&<section className="pipeline">{t.stages.map((stage,i)=><div className="pipeline-column" key={stage}><div className="stage-title">{stage}<span className="count-badge">{[3,4,3,2][i]}</span></div><article className="opportunity-card"><small>OPP-00{i+1}</small><h2>{['Customer portal','Operations workspace','Service dashboard','Project tracking'][i]}</h2><p>{customers[i][1]}</p><span className="badge active">{t.open}</span></article></div>)}</section>}
 {page==='users'&&<section className="data-panel"><div className="panel-title"><h2>{t.users}</h2><span className="muted">{t.demoData}</span></div><div className="profile-row"><span className="avatar">JD</span><div><strong>Demo Admin</strong><p>{t.admin} · {t.active}</p></div></div></section>}
 {page==='roles'&&<section className="role-grid">{['Admin','Sales Manager','Sales','Viewer'].map((role,i)=><article className="role-card" key={role}><ShieldCheck/><h2>{role}</h2><p>{t.roleDescriptions[i]}</p></article>)}</section>}
 {page==='profile'&&<section className="data-panel profile-panel"><span className="avatar large">JD</span><h2>Demo Admin</h2><p>{t.admin}</p><label>{t.language}</label><div className="profile-languages"><button aria-pressed={lang==='th'} onClick={()=>setLang('th')}>ไทย</button><button aria-pressed={lang==='en'} onClick={()=>setLang('en')}>English</button></div></section>}
 <div className="page-footnote"><span className="status-dot"/>{t.previewFooter}</div></main></SidebarInset></>;
}
export default function Home(){return <TooltipProvider><SidebarProvider><Workspace/></SidebarProvider></TooltipProvider>}
